# NumPy Basics

NumPy - short for numerical Python - is an essential foundational packages for numerical computing in Python. One of Numpy's primary use in data analysis applications is as a container for data to be passed between algorithms and libraries. NumPy is more efficient for storing and manipulating data than the other built-in Python data structures is because it is designed for efficiency on large arrays of data. Reasons for this are:

+ NumPy internally stores data in a contigious block of memory, independent of other built-in Python objects. It operate on this memory without any type checking or other overhead. NumPy also uses much less memory than other built-in Python sequences.
+ NumPy operations perform complex computations on entire arrays without the need for Python `for` loops.

Examples below illustrate the performance difference between computations on a NumPy array and a Python list:

In [1]:
import numpy as np

my_arr = np.arange(1_000_000)    # numpy array
my_list = list(range(1_000_000)) # Python list

# compute and display processing time for comparison
%time for _ in range(10): my_arr2 = my_arr*2
# time < 20 ms
    
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]
# time 400+ ms

CPU times: user 11.8 ms, sys: 3.62 ms, total: 15.4 ms
Wall time: 15.4 ms
CPU times: user 369 ms, sys: 54.4 ms, total: 424 ms
Wall time: 423 ms


## The NumPy *ndarray*

A key features of NumPy is its N-dimensional array object, or *ndarray* - a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax equivalent operations between scalar elements. Below are some examples of computations on NumPy arrays:

In [2]:
data = np.random.randn(2,3) # generate 2x3 array of random numbers
print(data)
print("")

# multiply all elements by 10 in the array
data * 10

# add each array element by itself, i.e. double the elements
data + data

[[ 0.07390336 -0.34478298  0.11112559]
 [ 2.34321772 -1.38892558 -1.27904173]]



array([[ 0.14780673, -0.68956596,  0.22225118],
       [ 4.68643545, -2.77785117, -2.55808347]])

### Creating *ndarrays*

Use the `array` function from the `numpy` class to create an array. For example:

In [3]:
data1 = [6, 7.5, 8, 0, 1]  # a list of numbers
print(data1)

arr1 = np.array(data1) # convert a list to numpy array
print(arr1)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]  # a nested list comprising list of numbers
print(data2)

arr2 = np.array(data2) # convert nested lists to numpy array
print(arr2)

[6, 7.5, 8, 0, 1]
[6.  7.5 8.  0.  1. ]
[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]


Inspecting dimensions of arrays:

In [4]:
# get n dimensions (i.e. rows)
print(arr2.ndim)
# 2

# get n rows and m columns
print(arr2.shape)
# (2, 4)

2
(2, 4)


In addition to `np.array`, there are other ways for creating new arrays. As examples, zeros and ones create arrays of 0s and 1s, respectively, with a given length or shape. `empty` creates an array without initialising its values to any particular value. To create higher dimensional array with these methods, pass a tuple for the shape:

In [5]:
# create array of 10 zeroes
x = np.zeros(10)
print(f"{x}\n")

# create 3x6 array of zeroes
x = np.zeros((3, 6))
print(f"{x}\n")

# create empty array of 2x3x2
x = np.empty((2, 3, 2))
print(f"{x}")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[[4.66868025e-310 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]]


**Note**: *`np.empty` does not set array values to zeroes; it may return uninitialised "garbage" values. It is marginally faster than zero array but on the other hand, it requires the user to manually set all the values in the array, thus should be used with caution.*

### Data Types for *ndarrays*

`dtypes` are a source of NumPy's flexibility for interacting with data coming from other systems. They facilitate the ndarray to interpret a chunk of memory as a particular type of data. The `numpy.array()` arrays will attempt to infer an appropriate data type for the array created. 

In [6]:
print(arr1.dtype)  # float64
print(arr2.dtype)  # int64

float64
int64


We can set the `dtype` when creating arrays like below:

In [7]:
arr1 = np.array([1, 2, 3], dtype=np.float64)  # generate array to store float values
arr2 = np.array([1, 2, 3], dtype=np.int32)    # generate array to store integer values

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In most cases, *dtypes* provide a mapping directly onto an underlying disk or memory representation, which makes it easy to read and write binary streams of data to disk and also to connect to code written in a low-level language like C or Fortran. A standard double-precision floating-point value takes up 8 or 64 bits. Thus, this type is know in Numpy as `float64`. Below is the full listing of NumPy's supported data types:

**Type** | **Type code** | **Description**
--- | --- | ---
int8, uint8 | i1, u1 | Signed and unsigned 8-bit (1 byte) integer types
int16, uint16 | i2, u2 | Signed and unsigned 16-bit integer types
int32, uint32 | i4, u4 | Signed and unsigned 32-bit integer types
int64, uint64 | i8, u8 | Signed and unsigned 64-bit integer types
--- | --- | ---
float16 | f2 | Half-precision floating point
float32 | f4 or f | Standard single-precision floating point; compatible with C float
float64 | f8 or d | Standard double-precision floating point; compatible with C double and Python float object
float128 | f16 or g | Extended-precision floating point
--- | --- | ---
complex64 | c8 | Complex numbers represented by two 32 floats 
complex128 | c16 | Complex numbers represented by two 64 floats 
complex256 | c32 | Complex numbers represented by two 128 floats 
--- | --- | ---
bool | ? | Boolean type storing `True` and `False` values
object | O | Python object type; a value can be any Python object
string_ | S | Fixed-length ASCII type (1 byte per character)
unicode_ | U | Fixed-length Unicode type (number of bytes platform specific)


You can explicitly convert or cast an array from one dtype to another, using `astype` method:

In [8]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype   
# dtype('int64')

# cast array to float64 type
float_arr = arr.astype(np.float64)  

float_arr.dtype  
# dtype('float64')


# casting from float to integer will truncate decimal part of values
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.dtype  
# dtype('float64')

arr.astype(np.int32)  
# array([3, -1, -2, 0, 12, 10])

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

**Note**: *Calling `astype` always create a new array(a copy of the data).*

## Basic Indexing and Slicing

Like Python lists, NumPy arrays also support indexing and slicing. For example:

In [9]:
arr = np.arange(10) # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[5])  # retrieve 6th elem

print(arr[5:8])  # retrieve 6th to 8th items in the array

arr[5:8] = 12

print(arr[5:8])

5
[5 6 7]
[12 12 12]


Accessing two-dimensional array:

In [10]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]
# [7, 8, 9]

arr2d[0, 2]
# 3

3

**Note:** Unlike a Python list, array slices are *view* on the original array. Thus any value modifications done to the slice will be reflected in the source array.

In [11]:
arr_slice = arr[5:8]  # obtain slice of 6th to 8th elements from array
arr_slice[1] = 12345  # modify 1st item in slice

print(arr_slice)

# changes in slice is reflected in the original array
print(arr)


# this assigns to all values in an array
arr_slice[:] = 12345

print(arr)

[   12 12345    12]
[    0     1     2     3     4    12 12345    12     8     9]
[    0     1     2     3     4 12345 12345 12345     8     9]


To prevent modifying the original array while working on array slices, you can use `copy()` method when slicing:

In [12]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# copy out the slice instead of getting just the "view"
old_values = arr3d[0].copy()  

# set values of first vector in the first dimension in the array to 42
arr3d[0] = 42  
print(arr3d)

# reset back to old values
arr3d[0] = old_values  
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Illustration of two-dimensional array slicing:

<img src="https://www.oreilly.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages2172114.png" width="300" />

### Boolean Indexing

Instead of numerical indexing, we can also use boolean indexing to select data from array in the examples below:

In [13]:
# generate NumPy array from a list of names
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

# generate random data array with number of rows corresponding to names.ndim (i.e. 7)
data = np.random.randn(7, 4)
print(data)
print("\n")

# return array of same shape comprising boolean result
names == 'Bob'
# array([ True, False, False,  True, False, False, False])


# get array rows based on earlier condition result
x = data[names == 'Bob']
print(f"{x}\n")

# return array rows based on false negatives of earlier condition result
x = data[~(names == 'Bob')]
print(f"{x}\n")

# does the same as previous one
x = data[names != 'Bob']
print(f"{x}\n")

[[ 0.80302169  0.8220963   0.25215869  1.34607905]
 [ 1.61088385 -0.36353469  0.06768078 -1.3080823 ]
 [ 0.65520616  1.24507517  0.54950267 -1.19989585]
 [-0.34729065  0.42589081  0.61766175  0.06964881]
 [-0.76242251  0.19231361 -1.44300562 -0.87409973]
 [ 0.1653121   1.23702947  0.78325728  0.3274351 ]
 [-1.0742759  -0.18754959 -1.00980082 -0.41422362]]


[[ 0.80302169  0.8220963   0.25215869  1.34607905]
 [-0.34729065  0.42589081  0.61766175  0.06964881]]

[[ 1.61088385 -0.36353469  0.06768078 -1.3080823 ]
 [ 0.65520616  1.24507517  0.54950267 -1.19989585]
 [-0.76242251  0.19231361 -1.44300562 -0.87409973]
 [ 0.1653121   1.23702947  0.78325728  0.3274351 ]
 [-1.0742759  -0.18754959 -1.00980082 -0.41422362]]

[[ 1.61088385 -0.36353469  0.06768078 -1.3080823 ]
 [ 0.65520616  1.24507517  0.54950267 -1.19989585]
 [-0.76242251  0.19231361 -1.44300562 -0.87409973]
 [ 0.1653121   1.23702947  0.78325728  0.3274351 ]
 [-1.0742759  -0.18754959 -1.00980082 -0.41422362]]



Combining multiple boolean conditions:

In [14]:
mask = (names == 'Bob') | (names == 'Will')  # get boolean results of either name is 'Bob' or 'Will' (in 1-d array)
# array([ True, False,  True,  True,  True, False, False])

# returns n-th row of data array corresponding to true values in 'mask' array 
data[mask]

array([[ 0.80302169,  0.8220963 ,  0.25215869,  1.34607905],
       [ 0.65520616,  1.24507517,  0.54950267, -1.19989585],
       [-0.34729065,  0.42589081,  0.61766175,  0.06964881],
       [-0.76242251,  0.19231361, -1.44300562, -0.87409973]])

In [15]:
# setting values less than zero in the array to zero
data[data < 0] = 0
print(f"{data}\n")

# setting values (in rows corresponding to names not Joe) in the array to 7
data[names != 'Joe'] = 7
print(data)

[[0.80302169 0.8220963  0.25215869 1.34607905]
 [1.61088385 0.         0.06768078 0.        ]
 [0.65520616 1.24507517 0.54950267 0.        ]
 [0.         0.42589081 0.61766175 0.06964881]
 [0.         0.19231361 0.         0.        ]
 [0.1653121  1.23702947 0.78325728 0.3274351 ]
 [0.         0.         0.         0.        ]]

[[7.         7.         7.         7.        ]
 [1.61088385 0.         0.06768078 0.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.1653121  1.23702947 0.78325728 0.3274351 ]
 [0.         0.         0.         0.        ]]


### Fancy Indexing

Fancy Indexing refers to indexing using integer arrays:

In [16]:
arr = np.arange(32).reshape((8, 4))   # generate series of 0-31 numbers and shape them into 8x4 array
print(f"{arr}\n")

## pass in [4, 3, 0, 6] as 1 argument
# get 5th, 4th, 1st and 7th rows of arr
x = arr[[4, 3, 0, 6]]
print(f"{x}\n")

# contrast with below code (less 1 pair of square brackets, which returns item in 5th row, 4th column
x = arr[4, 3]
print(f"{x}\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[16 17 18 19]
 [12 13 14 15]
 [ 0  1  2  3]
 [24 25 26 27]]

19



In the 2nd example above, we pass `[4, 3, 0, 6]` as the first argument for array indexing, which in turn will return array slice comprising the 5th, 4th, 1st and 7th rows (recall indices starts from zero in Python instead of 1) in that order. In the 3rd example, we pass in `4` as first argument and `3` as the second argument to retrieve the element residing in 5th row, 4th column of the array. 

Also note that fancy indexing *always copies* the data into a new array, unlike slicing.

More complex indexing examples below:

In [17]:
# retrieve the 1st, 4th, 2nd and 3rd elements from respective rows in the earlier data subarray
x = arr[[4, 3, 0, 6], [0, 3, 1, 2]]
print(f"{x}\n")

# retrieve the 4th column from the subarray specified by first argument: [4, 3, 0, 6]
x = arr[[4, 3, 0, 6], 3]
print(f"{x}\n")

# modifying the values in array returned by fancy indexing doesn't impact the original values
x = arr[[4, 3, 0, 6], 3]
x[0] = 1
print(arr)

[16 15  1 26]

[19 15  3 27]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


## Transposing Array, Swapping Axes

The transpose of a array returns a flipped view of the array over its diagonal, whereby the rows and columns are swapped. Transposing returns merely a *view* of the data thus modifying the returned transposed matrix will modify the original data. Arrays have the `transpose` method and also the special `T` attribute to facilitate the transpose operations:

In [18]:
# transpose matrix/array
arr = np.random.randn(6, 3)
print(arr)
print("\n---transposed form---")
print(arr.T)

# this does the same
print("\n---another way to transpose---")
print(arr.transpose(1, 0))   # reorder 2nd (y-axis) with the 1st (x-axis)

[[ 1.04702965e+00  1.31531103e+00  4.46790969e-02]
 [ 1.55020713e+00 -1.41248738e+00  1.10605763e+00]
 [-1.84217169e+00 -1.03036361e-01  8.31048399e-01]
 [-7.87183242e-04 -7.10269682e-03  8.46383428e-01]
 [ 6.17143990e-01 -5.80741372e-01  1.92924986e+00]
 [ 5.93229913e-01  5.36056621e-01  2.23776616e-01]]

---transposed form---
[[ 1.04702965e+00  1.55020713e+00 -1.84217169e+00 -7.87183242e-04
   6.17143990e-01  5.93229913e-01]
 [ 1.31531103e+00 -1.41248738e+00 -1.03036361e-01 -7.10269682e-03
  -5.80741372e-01  5.36056621e-01]
 [ 4.46790969e-02  1.10605763e+00  8.31048399e-01  8.46383428e-01
   1.92924986e+00  2.23776616e-01]]

---another way to transpose---
[[ 1.04702965e+00  1.55020713e+00 -1.84217169e+00 -7.87183242e-04
   6.17143990e-01  5.93229913e-01]
 [ 1.31531103e+00 -1.41248738e+00 -1.03036361e-01 -7.10269682e-03
  -5.80741372e-01  5.36056621e-01]
 [ 4.46790969e-02  1.10605763e+00  8.31048399e-01  8.46383428e-01
   1.92924986e+00  2.23776616e-01]]


You can easily perform inner matrix product computations using `np.dot`:

In [19]:
# computation using np.dot
np.dot(arr.T, arr)

array([[ 7.62579884, -0.66305834,  1.55317461],
       [-0.66305834,  4.36044789, -2.59560362],
       [ 1.55317461, -2.59560362,  6.40444704]])

### More complex array swap/transpose

For higher-dimensional arrays, you can use the `transpose` method that takes in a tuple of axes as an argument to permute the axes:

In [20]:
arr = np.arange(16).reshape((2, 2, 4))  # reshape into a 3-dimensional array
print(arr)

print("\n---1st axis, 1st item---")
print(arr[0])

print("\n---2nd axis, 1st item---")
print(arr[:,0])

print("\n---3rd axis, 1st item---")
print(arr[:,:,0])
print("\n")

# reorder axis: swap 2nd axis with the 1st
print(arr.transpose((1, 0, 2)))

# this does the same thing
arr.swapaxes(1, 0)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

---1st axis, 1st item---
[[0 1 2 3]
 [4 5 6 7]]

---2nd axis, 1st item---
[[ 0  1  2  3]
 [ 8  9 10 11]]

---3rd axis, 1st item---
[[ 0  4]
 [ 8 12]]


[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In the above example, the `swapaxes` method takes a pair of axis numbers and switches the indicated axes to rearrange the data:

## Array-Oriented Programming Methods/Functions

### Universal functions
NumPy provides for simple element-wise transformations via universal functions like `sqrt` or `exp`. These include unary and binary functions. Below are listing of available universal functions:

*Unary functions:*

**Function** | **Description**
--- | ---
`abs`, `fabs` | Compute the absolute value element-wise
`sqrt` | Compute square root of each element
`exp` | Compute the exponent of each element
`log`, `log10`, `log2`, `log1p` | Return the natural logarithm (base e), log base 10, log base 2, and log(1+x) respectively
`isnan` | Return True or False values indicating whether each element is NaN (Not a Number)
`isfinite`, `isinf` | Return True or False values indicating whether each element is finite or infinite, respectively
`sign` | Compute the sign of each element: 1 (positive); 0 (zero); -1 (negative)
`ceil` | Compute the ceiling of each element
`floor` |  Compute the floor of each element
`rint` | Round elements to the nearest integer, preserving `dtype`.
`modf` | Return fractional and integral parts of array as a separate array
`cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` | Regular and hyperbolic trigonometric functions
`arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` | Inverse trigonometric functions
`logical_not` | Compute truth value of `not` element-wise (same as `~arr`)


*Binary functions:*

**Function** | **Description**
--- | ---
`add` | Add corresponding elements in arrays
`subtract` |  Subtract elements in second array from first array
`multiply` | Multiply array elements
`divide`, `floor_divide` |  Divide or floor divide (trauncating the reminder)
`power` |  Raise elements in the first array to powers indicated in second array
`maximum`, `fmax` | Element-wise maximum; fmax ignores `NaN`
`minimum`, `fmin` | Element-wise minimum; fmin ignores `NaN`
`mod` | Element-wise modulus (remainder of division) 
`copysign` | Copy sign of values in second argument to values in first argument
`greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal` | Perform element-wise comparison, yielding boolean array (equivalent to infix operators `>`, `>=`, `<`, `<=`, `==`, `!=`)
`logical_and`, `logical_or`, `logical_xor` | Compute element-wise truth value of logical operation (equivalent to infix opertors `&`, `|`, `^`)

Some examples below:

In [21]:
x = np.random.randn(8)
y = np.random.randn(8)
print(f"x: {x}\n")
print(f"y: {y}\n")

# find maximum of the two element-wise
z = np.maximum(x, y)
print(f"--max--\n{z}\n")


# sep integral and remainder
remainder, whole_part = np.modf(x)
print(f"--remainder--\n{remainder}\n")
print(f"--whole_part--\n{whole_part}\n")


arr = np.random.randn(8) * 5
print(f"arr:\n{arr}")

# perform square root element-wise
print(f"\nsquare root:\n{np.sqrt(arr)}")

x: [-2.11117862 -1.38421483  0.78456578 -1.74191495  0.2979324   0.55283881
 -0.2356603   0.37043209]

y: [-0.40733503  1.61583361  0.31380518  0.96316142  1.84935993 -0.00380587
  0.3626372   0.12928428]

--max--
[-0.40733503  1.61583361  0.78456578  0.96316142  1.84935993  0.55283881
  0.3626372   0.37043209]

--remainder--
[-0.11117862 -0.38421483  0.78456578 -0.74191495  0.2979324   0.55283881
 -0.2356603   0.37043209]

--whole_part--
[-2. -1.  0. -1.  0.  0. -0.  0.]

arr:
[-0.30129098 14.2992103  -5.58044189  6.88271393  0.26160702  3.69593758
 -3.20925303 -7.81743112]

square root:
[       nan 3.78142966        nan 2.6234927  0.51147533 1.92248214
        nan        nan]


<ipython-input-21-10dab6600ca1>:21: RuntimeWarning: invalid value encountered in sqrt
  print(f"\nsquare root:\n{np.sqrt(arr)}")


*Note: ignore the warning above - this is due to the `sqrt` function encountering negative values which it is unable to get square root, thus it outputs `NaN` values.*

The above universal functions also accept an *out* parameter which assigns the result to the variable you pass in as the paremeter. You can thus make modifications to the arrays in-place by passing in the array object as the *out* argument:

In [22]:
newarr = np.zeros(8)  # generating zero array

np.sqrt(arr, newarr)  # assigns result to newarr 
print(newarr)
print()

print(arr)            # no modifications to the original array
print()

# square root on array elements in-place - modify the original values
np.sqrt(arr, arr) 
print(arr)

[       nan 3.78142966        nan 2.6234927  0.51147533 1.92248214
        nan        nan]

[-0.30129098 14.2992103  -5.58044189  6.88271393  0.26160702  3.69593758
 -3.20925303 -7.81743112]

[       nan 3.78142966        nan 2.6234927  0.51147533 1.92248214
        nan        nan]


<ipython-input-22-37f33fc132cf>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, newarr)  # assigns result to newarr
<ipython-input-22-37f33fc132cf>:11: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


### Mathematical and Statistical Methods

NumPy also supports aggregations like `sum`, `mean` and `std`. The listing of basic array statistical methods is as follow:

**Method** | **Description**
--- | ---
`sum` | Sum of all the elements in the array or along an axis
`mean` | Arithmethc mean; zero-length arrays have `NaN` mean
`std`, `var` | Compute the standard deviation and variance, respectively; optional degrees of freedoms adjustment can be specified
`min`, `max` | Compute the minimum and maximum
`argmin`, `argmax` | Indices of minimum and maximum elements, respectively
`cumsum` | Cumulative sum of elements starting from 0
`cumprod` | Cumulative products of elements starting from 1

You can invoke the methods like these:

In [23]:
arr = np.random.randn(4, 5)
print(arr)

print(arr.mean())  # compute mean

print(np.mean(arr))   # this does the same

print(arr.sum())  # compute sum

# combining with boolean condition and summation
(arr > 0).sum()

[[-1.02289679  0.33499658  0.96298714  0.23950081  1.1831631 ]
 [-0.60236877 -2.05474543  1.48942154  0.17082935  0.17749735]
 [-0.19265065 -1.10570313 -1.99371048  0.22089198 -0.9388767 ]
 [ 0.09014213  0.0151223  -0.16486228 -0.67178845  0.1872414 ]]
-0.1837904508764769
-0.1837904508764769
-3.6758090175295384


11

Some of these functions take an optional `axis` argument that computes over the given axis:

In [24]:
print(arr.mean(axis=1))  # compute mean across columns for each row

print(arr.mean(axis=0))  # compute mean across rows for each column

[ 0.33955017 -0.16387319 -0.8020098  -0.10882898]
[-0.43194352 -0.70258242  0.07345898 -0.01014158  0.15225629]


### `any` and `all` methods

`any` and `all` methods are useful especially for boolean arrays. `any` tests whether one or more values in an array is `True`, while `all` checks if every value is `True`. These methods also work with non-boolean arrays, where non-zero elements evaluted to `True`:

In [25]:
bools = np.array([False, False, True, False])

bools.any()
# True

bools.all()
# False

False

### Sorting

Like Python's built-in `list` type, NumPy arrays can be sorted in-place with the `sort` method:

In [26]:
arr = np.random.randn(6)
print(arr)

# sort in ascending order
arr.sort()
print(arr)

# reverse items to achieve descending sort order 
arr[::-1]

[ 0.49834781 -1.18482526 -1.42660612  0.12520968 -0.03206422 -0.58887238]
[-1.42660612 -1.18482526 -0.58887238 -0.03206422  0.12520968  0.49834781]


array([ 0.49834781,  0.12520968, -0.03206422, -0.58887238, -1.18482526,
       -1.42660612])

In [27]:
# practical example of using sort to compute quantile
large_arr = np.random.randn(1000)
large_arr.sort()

large_arr[int(0.05 * len(large_arr))]  # 5% quantile

-1.7296701389013371

You can sort each one-dimensional section of values in a multi-dimensional array in-place along an axis by passing the axis number to sort:

In [28]:
arr = np.random.randn(5, 3)
print(arr)

arr.sort(1)  # sort elements within each row
print(f"\n{arr}")

[[ 0.696008    0.63120932  0.27654188]
 [ 0.26259868 -0.67539874  0.53680632]
 [ 0.58511776 -0.35817726 -0.97035587]
 [ 0.18576395 -1.91013551  0.67378926]
 [ 0.16592759  1.25404482 -0.08799887]]

[[ 0.27654188  0.63120932  0.696008  ]
 [-0.67539874  0.26259868  0.53680632]
 [-0.97035587 -0.35817726  0.58511776]
 [-1.91013551  0.18576395  0.67378926]
 [-0.08799887  0.16592759  1.25404482]]


### Unique and Other Set Logic

NumPy has some basic set operations for one-dimensional ndarrays. One commonly used operation is `np.unique`, which returns the sorted unique values in an array:

In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

np.unique(names)
# ['Bob', 'Joe', 'Will']


# contrast this with pure Python alternative method
sorted(set(names))
# ['Bob', 'Joe', 'Will']

['Bob', 'Joe', 'Will']

Another useful set method is `np.in1d`, which tests membership of the values in one array in another, returning a boolean array:

In [30]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

A listing of set functions in NumPy:

**Method** | **Description**
--- | ---
unique(x) | Compute the sorted, unique elements in x
intersect1d(x, y) | Compute the sorted, common elements in x and y
union1d(x, y) |  Compute the sorted union of elements
in1d(x, y) | Compute a boolean array indicating whether each element of x is contained in y
setdiff1d(x, y) | Set difference, elements in x that are not in y
setxor1d(x, y | Set symmetric differences; elements that are in either of the arrays, but not both

### Linear Algebra

Linear algebra, like matrix manipulation, decompositions, determinants, and other square matrix math, is an important part of any array library. Below table lists some of the most commonly used linear algebra functions for Numpy:

**Function** | **Description**
--- | ---
`diag` | Return the diagonal elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal
`dot` | Matrix multiplication
`trace` | Compute the sum of the diagonal elements
`det` | Compute the matrix determinant
`eig` | Compute the eigenvalues and eigenvectors of a square matrix
`inv` | Compute the inverse of a square matrix
`pinv` | Compute the Moore-Penrose pseudo-inverse of a matrix

Some examples of numpy's linear algebra methods:

In [31]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

# matrix dot product
x.dot(y)
# array([[ 28.,  64.],
#        [ 67., 181.]])

# this is the same as 
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

## File Input and Output with Arrays

NumPy is able to save and load data to and from disk either in text or binary format. `np.save` and `np.load` are the two workhorse functions for efficiently saving and loading array data on disk. Arrays are saved by default in an uncompressed raw binary format with file extension *.npy*:

In [32]:
arr = np.arange(10)

# save array into binary file, 'some_array.npy'
np.save('some_array', arr)

# load array from file
x = np.load('some_array.npy')


# saving multiple arrays in an uncompressed archive using np.savez
np.savez('array_archive.npz', a=arr, b=arr)

# loading .npz file
arch = np.load('array_archive.npz')
arch['b']
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# saving in compressed archvie with numpy.savez_compressed instead
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

## Pseudorandom Number Generation

You have already seen the use of `numpy.random` in the earlier examples. The `numpy.random` module supplements the built-in Python `random` with functions for efficiently generating whole arrays of sample values from various kinds of probability distributions. Python's built-in `random` module, by contrast, only samples one value at a time. Thus `numpy.random` is more suited for generating very large samples as shown below:

In [33]:
from random import normalvariate

N = 1_000_000

# using built-in random for sample value generation
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

# using numpy's random for sample value generation
%timeit np.random.normal(size=N)

665 ms ± 7.89 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
23.2 ms ± 266 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [34]:
# generating 4x4 array of values from standard normal distribution
samples = np.random.normal(size=(4, 4))

The *pseudorandom* numbers are generated by an algorithm with deterministic behaviour based on the *seed* of the random number generator. You can change NumPy's random number generation seed as follow:

In [35]:
# setting global random seed
np.random.seed(1234)

# setting a local random seed
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

Table partially lists functions available in `numpy.random` module:

**Function** | **Description**
--- | ---
`seed` | Seed the random number generator
`permutation` | Return a random permutation of a sequence, or return a permutated range
`shuffle` | Randomly permute a sequence in-place
`rand` | Draw samples from a uniform distribution
`randint` | Draw random integers from a given low-to-high range
`randn` | Draw samples from a normal distribution with mean 0 and standard deviation 1
`binomial` | Draw samples from a binomial distribution
`normal` | Draw samples from a normal (Gaussian) distribution
`beta`  | Draw samples from a beta distribution
`chisquare` | Draw samples from a chi-square distribution
`gamma` | Draw samples from a gamma distribution
`uniform` | Draw samples from a uniform [0,1) distribution